apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sieve
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sieve
    spec:
      containers:
        - image: asia.gcr.io/ggv-notetool/sieve:latest
          imagePullPolicy: Always
          name: sieve
          volumeMounts:
          - name: config-volume
            mountPath: /config
          resources:
            requests:
              memory: "8Mi"
              cpu: "10m"
      terminationGracePeriodSeconds: 60
      volumes:
        - name: config-volume
          configMap:
            name: sieve-config
